parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module
env:
  browser: true
extends:
  - 'airbnb'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
  - 'prettier/react'
  - 'prettier/@typescript-eslint'
plugins:
  - 'react'
  - 'react-native'
  - 'prettier'
  - '@emotion'
settings:
  react:
    version: 'detect'
